#!/bin/bash
#
# Usage: send_speech <filename.flac>
#

URL="https://www.google.com/speech-api/v1/recognize?lang=$LANG&client=chromium"

if [ -z "$1" ];then
    echo ""
    exit 1
fi

wget -qO- --post-file "$1" --header 'Content-type: audio/x-flac; rate=16000' "$URL" > result.json

RESULT="$(cat result.json | sed 's/^[^[]*\[{\"utterance\":\"\([^\"]*\)\".*/\1/')"

echo "$RESULT"
