#!/bin/bash
#
# Usage: send_speech <filename.flac>
#
# Input file must be .flac, at rate 16000
# Google returns a file is in the form
# {"status":0,"id":"","hypotheses":[{"utterance":"some text here","confidence":0.7664485}]}
# which can be empty:
# {"status":5,"id":"","hypotheses":[]}
# the more, the result file can contain many of such lines! We take the first one only.
 
#FIXME: using $LANG from environment
URL="https://www.google.com/speech-api/v1/recognize?lang=$LANG&client=chromium"

FILEFOLDER=/tmp/lispeak
FILE=$FILEFOLDER/result.json
FILE1=$FILEFOLDER/result1.json

mkdir -p $FILEFOLDER
> $FILE
> $FILE1

if [ -z "$1" ];then
    echo ""
    exit 1
fi

wget -qO- --post-file "$1" --header 'Content-type: audio/x-flac; rate=16000' "$URL" > $FILE

head -n 1 $FILE > $FILE1

if [ \( ! -z "$(cat ${FILE1})" \) -a \( -z "$(cat ${FILE1} | sed 's/^[^[]*\[{\"utterance\".*//')" \) ];
then
   RESULT="$(cat ${FILE1} | sed 's/^[^[]*\[{\"utterance\":\"\([^\"]*\)\".*/\1/')"
else
   RESULT=""
fi

echo $RESULT

