#!/bin/bash

cd ${0%/*}

shopt -s nullglob
for f in *.pid
do
    echo $f
    base=$(basename $f)
	read PID < $f
	kill $PID
	rm $f
done

cp "./lispeak" "$HOME/.lispeak/bin/lispeak.py"
cp "./lispeak" "$HOME/.lispeak/services/lispeak.py"
cp "./lispeak" "./Recognition/bin/lispeak.py"
cp "./lispeak" "./Microphone/lispeak.py"

cp "./Setup/libraries/goslate.py" "$HOME/.lispeak/bin/"
cp "./Setup/libraries/goslate.py" "$HOME/.lispeak/services/"
cp "./Setup/libraries/goslate.py" "./Microphone/"

./Microphone/osd_server.py 2>/dev/null &disown
echo $! > "osd.pid"
./Microphone/indicator_server.py 2>/dev/null &disown
echo $! > "indicator.pid"

shopt -s nullglob
for f in $HOME/.lispeak/services/*.service
do
    echo $f
    base=$(basename $f)t
    $f &disown
    echo $! > "$base.pid"
done
