#!/bin/bash

#thanks to http://stackoverflow.com/questions/59895
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
cd $( dirname "$SOURCE" )


if [ "$1" = "-wait" ] ;
then
  sleep 10s
fi

./stop

FILEFOLDER=/tmp/lispeak_$(id -un)
mkdir -p $FILEFOLDER

./Microphone/notify.py 2>/dev/null &disown
echo $! > $FILEFOLDER/notify.pid
./Microphone/indicator_server.py 2>/dev/null &disown
echo $! > $FILEFOLDER/indicator.pid

shopt -s nullglob
for f in $HOME/.lispeak/services/*.service
do
    echo $f
    base=$(basename $f)
    $f &disown
    echo $! > $FILEFOLDER/$base.pid
done

