#!/bin/bash

#thanks to http://stackoverflow.com/questions/59895
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
cd $( dirname "$SOURCE" )

FILEFOLDER=/tmp/lispeak_$(id -un)

shopt -s nullglob
for f in $FILEFOLDER/*.pid
do
    echo $f
    base=$(basename $f)
	read PID < $f
	kill $PID 2&>/dev/null
	rm -f $f
done

